return {
	Title = "运行时助手",
	FrontendPlugins = {
		[1] = "InGameHelperFrontend.dll",
	},
	BackendPlugins = {
		[1] = "InGameHelperBackend.dll",
	},
	Source = 0,
	FileId = 2,
	Version = "0.0.1.0",
	GameVersion = "0.84.54-test",
	Author = "风尘骑",
	Description = "",
	WorkshopCover = nil,
	TagList = {
	},
	Visibility = 0,
	DefaultSettings = {
	},
	SettingGroups = {
	},
	UpdateLogList = { },
	ChangeConfig = false,
	HasArchive = false,
	NeedRestartWhenSettingChanged = false,
}
