<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\The Scroll Of Taiwu\The Scroll of Taiwu_Data\Managed\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="GameData">
      <HintPath>..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\The Scroll Of Taiwu\Backend\GameData.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="GameData.Shared">
      <HintPath>..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\The Scroll Of Taiwu\Backend\GameData.Shared.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="NLog">
      <HintPath>..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\The Scroll Of Taiwu\Backend\NLog.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Redzen">
      <HintPath>..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\The Scroll Of Taiwu\Backend\Redzen.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaiwuModdingLib">
      <HintPath>..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\The Scroll Of Taiwu\The Scroll of Taiwu_Data\Managed\TaiwuModdingLib.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
